name: pubspec_lock
description: Dart library to access and manipulate content of pubpec.lock files
version: 3.0.2
homepage: https://github.com/alexei-sintotski/pubspec_lock

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  functional_data: ^1.0.0
  json2yaml: ^3.0.0
  meta: ^1.7.0
  sum_types: ^0.3.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.0
  dependency_validator: ^3.1.0
  functional_data_generator: ^1.1.0
  sum_types_generator: ^0.3.0
  test: ^1.18.0
