name: pubspec_lock
description: Dart library to access and manipulate content of pubpec.lock files
version: 2.0.1
homepage: https://github.com/alexei-sintotski/pubspec_lock

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  functional_data: ^0.3.0
  json2yaml: ^1.0.1
  sum_types: ^0.2.1
  yaml: ^2.2.0

dev_dependencies:
  build_runner: ^1.7.2
  dependency_validator: ^1.4.2
  functional_data_generator: ^0.3.0
  sum_types_generator: ^0.2.1
  test: ^1.9.4
  test_coverage: ^0.4.0
